# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for Movs
    target 'MovsTests' do
    inherit! :search_paths
    # Pods for testing
        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end


end
