# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileChallengeCIET' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileChallengeCIET
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'AlamofireImage', '~> 3.5'

  target 'MobileChallengeCIETTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileChallengeCIETUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
