# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie

  pod 'Alamofire', '~> 5.0.0-beta.6'
  pod 'Kingfisher', '~> 5.0'

end
