# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieApp
  pod 'Moya'
  pod 'Kingfisher'
  
  target 'TheMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
