# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moviesTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moviesTest

  pod 'Alamofire', '~> 4.0.0-rc.3'
  pod 'Kingfisher', '~> 4.0'

end
